### ISSUE TITLE
GCM Dependency Conflict!

### ISSUE THREAD

**Issue by dcflow** [zetavg/react-native-system-notification#16]
Hi,

Your package requires `play-services-gcm:8.1` and the rn gcm package requires the `8.3` version. 
There should be a different solution than adding the gcm package as a peer.

Thank You!

**Comment by Neson** [comment]
I've discussed this with the author of gcm package a few days ago, I'll fix this by adding a dependency to gcm package and issue a PR to remove the notification dependency on gcm package. Thank you for reporting!
